docs: convert useListenFocusTriggers stories file to TS
mondaycom/vibe pull request #2492
Opened 2024-10-11 12:25 UTC by LoayTarek5

Here are the main changes made to convert the code to TypeScript:
Added type annotation for the text state: useState<string>("-").
Specified the type for the ref: useRef<HTMLButtonElement>(null).
Added type annotations for the event parameters in onFocusByMouse and onFocusByKeyboard: React.FocusEvent<HTMLButtonElement>.
Added an empty interface RenderProps which can be extended later if needed.
Added as const to the Overview object to ensure type inference for its properties.
#2474 
- [x] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

2024-10-13 00:26 UTC, LoayTarek5 commented
@LastExileUA @virtser @doronbrikman @jasonbahl 
could some one look at it😃

2024-10-13 15:07 UTC, talkor requested changes
@LoayTarek5 thank you for this PR! Looks like there are two similar files and the previous one is missing in this changeset (which means it's not deleted). Let's add the deletion of the old file, and keep only the tsx file here
Thanks!

2024-10-15 15:01 UTC, talkor commented
@LoayTarek5 there is still the old file :(

2024-10-16 07:04 UTC, talkor reviewed
Great @LoayTarek5 ! Just check out my 2 comments, probably unused code

2024-10-16 07:04 UTC, talkor commented on packages/core/src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.tsx
> +interface RenderProps {}
Looks like it's unused :)

2024-10-16 07:04 UTC, talkor commented on packages/core/src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.tsx
> +} as const;
I don't think it's needed

2024-10-20 10:19 UTC, talkor approved these changes
Thank you @LoayTarek5 ! Looks good, please just run prettier on this file as the CI fails for the extra spaces in line 7 
Thanks!

2024-11-03 09:45 UTC, merged