Removed Story Component from Spacing docs
mondaycom/vibe pull request #2533
Opened 2024-10-13 20:03 UTC by vaibhavj2111

Closes #2498

- [x] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

Resolves #2498

2024-10-14 06:32 UTC, YossiSaadi requested changes
Thanks @vaibhavj2111 ! had some comments :)

2024-10-14 06:32 UTC, YossiSaadi commented on packages/core/src/storybook/stand-alone-documentaion/spacing/Spacing.mdx
> +/>
seem like a mistake, can you remove this one please?

2024-10-14 06:32 UTC, YossiSaadi commented on packages/core/src/storybook/stand-alone-documentaion/spacing/Spacing.mdx
> +<Canvas of={SpacingStories.Sizes} sourceState="none">
Make the Canvas tag a self-closing one :)

2024-10-14 06:32 UTC, YossiSaadi commented on packages/core/src/storybook/stand-alone-documentaion/spacing/spacing.stories.tsx
> +  };
can you please run prettier on this file? it is missing a new line at the end of the file

2024-10-14 06:32 UTC, YossiSaadi commented on packages/core/src/storybook/stand-alone-documentaion/spacing/spacing.stories.tsx
> +import { StoryObj , Meta } from "@storybook/blocks";
Those should be imported from @storybook/react

2024-10-15 10:19 UTC, YossiSaadi requested changes
Great @vaibhavj2111!
I had a few comments on unclear changes:
- Please revert the package.json changes
- Please revert the yarn.lock changes
- Please remove the package-lock.json file

2024-10-15 10:19 UTC, YossiSaadi commented on package-lock.json
Can you please remove the package lock file?

2024-10-15 10:19 UTC, YossiSaadi commented on package.json
> +  }
also this dependency is redundant, we don't need it here 🙂

2024-10-15 10:19 UTC, YossiSaadi commented on yarn.lock
The yarn.lock also shouldn't have been changed

2024-10-15 12:01 UTC, vaibhavj2111 commented on yarn.lock
I didn't change anything in it, what exactly to revert in it??

2024-10-15 12:03 UTC, YossiSaadi commented on yarn.lock
you've added dependency of yarn by mistake 
also, you ran "npm install" probably, instead of "yarn", so it created a package lock file

2024-10-15 12:05 UTC, YossiSaadi commented
please rollback the yarn.lock changes, and reset its content to be the same as in vibe's master branch 🙏🏼

2024-10-15 12:59 UTC, YossiSaadi commented
@vaibhavj2111 Your PR still includes changes to the yarn.lock
![image](https://github.com/user-attachments/assets/a85a08a0-9a33-48b5-b062-8ea7f1d2c200)

You should copy the content of the yarn.lock to be the same as it is in `master`.
You can do it with for example with running from the root of the project the following command:
```
git checkout dbfc6dfbc4464ecb0aa4913fef74aa6d25fb8287 -- yarn.lock
```
this should revert the state of the `yarn.lock` file to be the same as in commit `dbfc6dfbc4464ecb0aa4913fef74aa6d25fb8287`, which is your initial commit in this PR (where no changes to yarn.lock applied, which is good)

2024-10-20 08:12 UTC, YossiSaadi approved these changes
Awesome @vaibhavj2111 ! Thanks for your contribution to Vibe!

2024-10-20 08:13 UTC, merged